// flow-typed signature: 1cc2f9935e5c9ed5a448472918a31d4f
// flow-typed version: <<STUB>>/jest-plugins_v^2.9.0/flow_v0.89.0

/**
 * This is an autogenerated libdef stub for:
 *
 *   'jest-plugins'
 *
 * Fill this stub out by replacing all the `any` types.
 *
 * Once filled out, we encourage you to share your work with the
 * community by sending a pull request to:
 * https://github.com/flowtype/flow-typed
 */

declare module 'jest-plugins' {
  declare module.exports: any;
}

/**
 * We include stubs for each file inside this npm package in case you need to
 * require those files directly. Feel free to delete any files that aren't
 * needed.
 */
declare module 'jest-plugins/build/install' {
  declare module.exports: any;
}

declare module 'jest-plugins/setup' {
  declare module.exports: any;
}

// Filename aliases
declare module 'jest-plugins/build/install.js' {
  declare module.exports: $Exports<'jest-plugins/build/install'>;
}
declare module 'jest-plugins/setup.js' {
  declare module.exports: $Exports<'jest-plugins/setup'>;
}
