// flow-typed signature: eaef9836f50ad0c19a3b5cd612371264
// flow-typed version: <<STUB>>/jest-plugin-action_v^2.9.0/flow_v0.90.0

/**
 * This is an autogenerated libdef stub for:
 *
 *   'jest-plugin-action'
 *
 * Fill this stub out by replacing all the `any` types.
 *
 * Once filled out, we encourage you to share your work with the
 * community by sending a pull request to:
 * https://github.com/flowtype/flow-typed
 */

declare module 'jest-plugin-action' {
  declare module.exports: any;
}

/**
 * We include stubs for each file inside this npm package in case you need to
 * require those files directly. Feel free to delete any files that aren't
 * needed.
 */
declare module 'jest-plugin-action/build/action' {
  declare module.exports: any;
}

declare module 'jest-plugin-action/setup' {
  declare module.exports: any;
}

// Filename aliases
declare module 'jest-plugin-action/build/action.js' {
  declare module.exports: $Exports<'jest-plugin-action/build/action'>;
}
declare module 'jest-plugin-action/setup.js' {
  declare module.exports: $Exports<'jest-plugin-action/setup'>;
}
