// flow-typed signature: 5a26e2694f44aab308f6e4dbc1cad046
// flow-typed version: <<STUB>>/jest-plugin-set_v^2.9.0/flow_v0.87.0

/**
 * This is an autogenerated libdef stub for:
 *
 *   'jest-plugin-set'
 *
 * Fill this stub out by replacing all the `any` types.
 *
 * Once filled out, we encourage you to share your work with the
 * community by sending a pull request to:
 * https://github.com/flowtype/flow-typed
 */

declare module 'jest-plugin-set' {
  declare module.exports: any;
}

/**
 * We include stubs for each file inside this npm package in case you need to
 * require those files directly. Feel free to delete any files that aren't
 * needed.
 */
declare module 'jest-plugin-set/build/define' {
  declare module.exports: any;
}

declare module 'jest-plugin-set/build/set' {
  declare module.exports: any;
}

declare module 'jest-plugin-set/build/undefine' {
  declare module.exports: any;
}

declare module 'jest-plugin-set/setup' {
  declare module.exports: any;
}

// Filename aliases
declare module 'jest-plugin-set/build/define.js' {
  declare module.exports: $Exports<'jest-plugin-set/build/define'>;
}
declare module 'jest-plugin-set/build/set.js' {
  declare module.exports: $Exports<'jest-plugin-set/build/set'>;
}
declare module 'jest-plugin-set/build/undefine.js' {
  declare module.exports: $Exports<'jest-plugin-set/build/undefine'>;
}
declare module 'jest-plugin-set/setup.js' {
  declare module.exports: $Exports<'jest-plugin-set/setup'>;
}
