// flow-typed signature: 28224a7a9e351f6089d48cfcafa07462
// flow-typed version: <<STUB>>/jest-plugin-unhandled-promise_v^2.9.0/flow_v0.90.0

/**
 * This is an autogenerated libdef stub for:
 *
 *   'jest-plugin-unhandled-promise'
 *
 * Fill this stub out by replacing all the `any` types.
 *
 * Once filled out, we encourage you to share your work with the
 * community by sending a pull request to:
 * https://github.com/flowtype/flow-typed
 */

declare module 'jest-plugin-unhandled-promise' {
  declare module.exports: any;
}

/**
 * We include stubs for each file inside this npm package in case you need to
 * require those files directly. Feel free to delete any files that aren't
 * needed.
 */
declare module 'jest-plugin-unhandled-promise/build/install' {
  declare module.exports: any;
}

declare module 'jest-plugin-unhandled-promise/setup' {
  declare module.exports: any;
}

// Filename aliases
declare module 'jest-plugin-unhandled-promise/build/install.js' {
  declare module.exports: $Exports<'jest-plugin-unhandled-promise/build/install'>;
}
declare module 'jest-plugin-unhandled-promise/setup.js' {
  declare module.exports: $Exports<'jest-plugin-unhandled-promise/setup'>;
}
