// flow-typed signature: 4429a39059f15cb89e2c6995ce96c169
// flow-typed version: <<STUB>>/jest-plugins-react_v^2.9.0/flow_v0.90.0

/**
 * This is an autogenerated libdef stub for:
 *
 *   'jest-plugins-react'
 *
 * Fill this stub out by replacing all the `any` types.
 *
 * Once filled out, we encourage you to share your work with the
 * community by sending a pull request to:
 * https://github.com/flowtype/flow-typed
 */

declare module 'jest-plugins-react' {
  declare module.exports: any;
}

/**
 * We include stubs for each file inside this npm package in case you need to
 * require those files directly. Feel free to delete any files that aren't
 * needed.
 */
declare module 'jest-plugins-react/setup' {
  declare module.exports: any;
}

// Filename aliases
declare module 'jest-plugins-react/setup.js' {
  declare module.exports: $Exports<'jest-plugins-react/setup'>;
}
