// flow-typed signature: a09e2c6470947457af1026a3cb6bc45a
// flow-typed version: <<STUB>>/jest-plugin-it-renders_v^2.9.0/flow_v0.89.0

/**
 * This is an autogenerated libdef stub for:
 *
 *   'jest-plugin-it-renders'
 *
 * Fill this stub out by replacing all the `any` types.
 *
 * Once filled out, we encourage you to share your work with the
 * community by sending a pull request to:
 * https://github.com/flowtype/flow-typed
 */

declare module 'jest-plugin-it-renders' {
  declare module.exports: any;
}

/**
 * We include stubs for each file inside this npm package in case you need to
 * require those files directly. Feel free to delete any files that aren't
 * needed.
 */
declare module 'jest-plugin-it-renders/build/itRenders' {
  declare module.exports: any;
}

declare module 'jest-plugin-it-renders/setup' {
  declare module.exports: any;
}

// Filename aliases
declare module 'jest-plugin-it-renders/build/itRenders.js' {
  declare module.exports: $Exports<'jest-plugin-it-renders/build/itRenders'>;
}
declare module 'jest-plugin-it-renders/setup.js' {
  declare module.exports: $Exports<'jest-plugin-it-renders/setup'>;
}
