// flow-typed signature: 0fad730c454f08ea5d48bb930b8318a9
// flow-typed version: <<STUB>>/pure-react-carousel_v^1.17.0/flow_v0.89.0

/**
 * This is an autogenerated libdef stub for:
 *
 *   'pure-react-carousel'
 *
 * Fill this stub out by replacing all the `any` types.
 *
 * Once filled out, we encourage you to share your work with the
 * community by sending a pull request to:
 * https://github.com/flowtype/flow-typed
 */

declare module 'pure-react-carousel' {
  declare module.exports: any;
}

/**
 * We include stubs for each file inside this npm package in case you need to
 * require those files directly. Feel free to delete any files that aren't
 * needed.
 */
declare module 'pure-react-carousel/__mocks__/fileMock' {
  declare module.exports: any;
}

declare module 'pure-react-carousel/dist/index.cjs' {
  declare module.exports: any;
}

declare module 'pure-react-carousel/dist/index.es' {
  declare module.exports: any;
}

declare module 'pure-react-carousel/postbuild' {
  declare module.exports: any;
}

declare module 'pure-react-carousel/rollup.config.cjs' {
  declare module.exports: any;
}

declare module 'pure-react-carousel/rollup.config.dev' {
  declare module.exports: any;
}

declare module 'pure-react-carousel/rollup.config.es' {
  declare module.exports: any;
}

declare module 'pure-react-carousel/src/__tests__/general.test' {
  declare module.exports: any;
}

declare module 'pure-react-carousel/src/app' {
  declare module.exports: any;
}

declare module 'pure-react-carousel/src/App/__tests__/App.test' {
  declare module.exports: any;
}

declare module 'pure-react-carousel/src/App/App' {
  declare module.exports: any;
}

declare module 'pure-react-carousel/src/App/examples/Example1/Example1' {
  declare module.exports: any;
}

declare module 'pure-react-carousel/src/App/examples/Example1/index' {
  declare module.exports: any;
}

declare module 'pure-react-carousel/src/App/examples/Example10/CustomSpinner' {
  declare module.exports: any;
}

declare module 'pure-react-carousel/src/App/examples/Example10/Example10' {
  declare module.exports: any;
}

declare module 'pure-react-carousel/src/App/examples/Example10/index' {
  declare module.exports: any;
}

declare module 'pure-react-carousel/src/App/examples/Example2/Example2' {
  declare module.exports: any;
}

declare module 'pure-react-carousel/src/App/examples/Example2/index' {
  declare module.exports: any;
}

declare module 'pure-react-carousel/src/App/examples/Example3/Example3' {
  declare module.exports: any;
}

declare module 'pure-react-carousel/src/App/examples/Example3/index' {
  declare module.exports: any;
}

declare module 'pure-react-carousel/src/App/examples/Example4/Example4' {
  declare module.exports: any;
}

declare module 'pure-react-carousel/src/App/examples/Example4/index' {
  declare module.exports: any;
}

declare module 'pure-react-carousel/src/App/examples/Example5/Example5' {
  declare module.exports: any;
}

declare module 'pure-react-carousel/src/App/examples/Example5/index' {
  declare module.exports: any;
}

declare module 'pure-react-carousel/src/App/examples/Example6/Example6' {
  declare module.exports: any;
}

declare module 'pure-react-carousel/src/App/examples/Example6/index' {
  declare module.exports: any;
}

declare module 'pure-react-carousel/src/App/examples/Example7/Example7' {
  declare module.exports: any;
}

declare module 'pure-react-carousel/src/App/examples/Example7/index' {
  declare module.exports: any;
}

declare module 'pure-react-carousel/src/App/examples/Example7/redux/demo-dux' {
  declare module.exports: any;
}

declare module 'pure-react-carousel/src/App/examples/Example7/redux/demo-store' {
  declare module.exports: any;
}

declare module 'pure-react-carousel/src/App/examples/Example7/SlideComponent/index' {
  declare module.exports: any;
}

declare module 'pure-react-carousel/src/App/examples/Example7/SlideComponent/SlideComponent' {
  declare module.exports: any;
}

declare module 'pure-react-carousel/src/App/examples/Example8/Example8' {
  declare module.exports: any;
}

declare module 'pure-react-carousel/src/App/examples/Example8/index' {
  declare module.exports: any;
}

declare module 'pure-react-carousel/src/App/examples/Example9/Example9' {
  declare module.exports: any;
}

declare module 'pure-react-carousel/src/App/examples/Example9/index' {
  declare module.exports: any;
}

declare module 'pure-react-carousel/src/App/examples/index' {
  declare module.exports: any;
}

declare module 'pure-react-carousel/src/ButtonBack/__tests__/ButtonBack.test' {
  declare module.exports: any;
}

declare module 'pure-react-carousel/src/ButtonBack/ButtonBack' {
  declare module.exports: any;
}

declare module 'pure-react-carousel/src/ButtonBack/index' {
  declare module.exports: any;
}

declare module 'pure-react-carousel/src/ButtonFirst/__tests__/ButtonFirst.test' {
  declare module.exports: any;
}

declare module 'pure-react-carousel/src/ButtonFirst/ButtonFirst' {
  declare module.exports: any;
}

declare module 'pure-react-carousel/src/ButtonFirst/index' {
  declare module.exports: any;
}

declare module 'pure-react-carousel/src/ButtonLast/__tests__/ButtonLast.test' {
  declare module.exports: any;
}

declare module 'pure-react-carousel/src/ButtonLast/ButtonLast' {
  declare module.exports: any;
}

declare module 'pure-react-carousel/src/ButtonLast/index' {
  declare module.exports: any;
}

declare module 'pure-react-carousel/src/ButtonNext/__tests__/ButtonNext.test' {
  declare module.exports: any;
}

declare module 'pure-react-carousel/src/ButtonNext/ButtonNext' {
  declare module.exports: any;
}

declare module 'pure-react-carousel/src/ButtonNext/index' {
  declare module.exports: any;
}

declare module 'pure-react-carousel/src/ButtonPlay/__tests__/ButtonPlay.test' {
  declare module.exports: any;
}

declare module 'pure-react-carousel/src/ButtonPlay/ButtonPlay' {
  declare module.exports: any;
}

declare module 'pure-react-carousel/src/ButtonPlay/index' {
  declare module.exports: any;
}

declare module 'pure-react-carousel/src/CarouselProvider/__tests__/CarouselProvider.test' {
  declare module.exports: any;
}

declare module 'pure-react-carousel/src/CarouselProvider/CarouselProvider' {
  declare module.exports: any;
}

declare module 'pure-react-carousel/src/CarouselProvider/index' {
  declare module.exports: any;
}

declare module 'pure-react-carousel/src/Dot/__tests__/Dot.test' {
  declare module.exports: any;
}

declare module 'pure-react-carousel/src/Dot/Dot' {
  declare module.exports: any;
}

declare module 'pure-react-carousel/src/Dot/index' {
  declare module.exports: any;
}

declare module 'pure-react-carousel/src/DotGroup/__tests__/DotGroup.test' {
  declare module.exports: any;
}

declare module 'pure-react-carousel/src/DotGroup/DotGroup' {
  declare module.exports: any;
}

declare module 'pure-react-carousel/src/DotGroup/index' {
  declare module.exports: any;
}

declare module 'pure-react-carousel/src/helpers/component-config' {
  declare module.exports: any;
}

declare module 'pure-react-carousel/src/helpers/index' {
  declare module.exports: any;
}

declare module 'pure-react-carousel/src/Image/__tests__/Image.test' {
  declare module.exports: any;
}

declare module 'pure-react-carousel/src/Image/Image' {
  declare module.exports: any;
}

declare module 'pure-react-carousel/src/Image/index' {
  declare module.exports: any;
}

declare module 'pure-react-carousel/src/ImageWithZoom/__tests__/ImageWithZoom.test' {
  declare module.exports: any;
}

declare module 'pure-react-carousel/src/ImageWithZoom/ImageWithZoom' {
  declare module.exports: any;
}

declare module 'pure-react-carousel/src/ImageWithZoom/index' {
  declare module.exports: any;
}

declare module 'pure-react-carousel/src/index' {
  declare module.exports: any;
}

declare module 'pure-react-carousel/src/Slide/__tests__/Slide.test' {
  declare module.exports: any;
}

declare module 'pure-react-carousel/src/Slide/index' {
  declare module.exports: any;
}

declare module 'pure-react-carousel/src/Slide/Slide' {
  declare module.exports: any;
}

declare module 'pure-react-carousel/src/Slider/__tests__/Slider.test' {
  declare module.exports: any;
}

declare module 'pure-react-carousel/src/Slider/GetScrollParent' {
  declare module.exports: any;
}

declare module 'pure-react-carousel/src/Slider/index' {
  declare module.exports: any;
}

declare module 'pure-react-carousel/src/Slider/Slider' {
  declare module.exports: any;
}

declare module 'pure-react-carousel/src/Spinner/index' {
  declare module.exports: any;
}

declare module 'pure-react-carousel/src/Spinner/Spinner' {
  declare module.exports: any;
}

declare module 'pure-react-carousel/src/Store/__tests__/Store.test' {
  declare module.exports: any;
}

declare module 'pure-react-carousel/src/Store/Store' {
  declare module.exports: any;
}

declare module 'pure-react-carousel/src/Store/WithStore' {
  declare module.exports: any;
}

// Filename aliases
declare module 'pure-react-carousel/__mocks__/fileMock.js' {
  declare module.exports: $Exports<'pure-react-carousel/__mocks__/fileMock'>;
}
declare module 'pure-react-carousel/dist/index.cjs.js' {
  declare module.exports: $Exports<'pure-react-carousel/dist/index.cjs'>;
}
declare module 'pure-react-carousel/dist/index.es.js' {
  declare module.exports: $Exports<'pure-react-carousel/dist/index.es'>;
}
declare module 'pure-react-carousel/postbuild.js' {
  declare module.exports: $Exports<'pure-react-carousel/postbuild'>;
}
declare module 'pure-react-carousel/rollup.config.cjs.js' {
  declare module.exports: $Exports<'pure-react-carousel/rollup.config.cjs'>;
}
declare module 'pure-react-carousel/rollup.config.dev.js' {
  declare module.exports: $Exports<'pure-react-carousel/rollup.config.dev'>;
}
declare module 'pure-react-carousel/rollup.config.es.js' {
  declare module.exports: $Exports<'pure-react-carousel/rollup.config.es'>;
}
declare module 'pure-react-carousel/src/__tests__/general.test.jsx' {
  declare module.exports: $Exports<'pure-react-carousel/src/__tests__/general.test'>;
}
declare module 'pure-react-carousel/src/app.js' {
  declare module.exports: $Exports<'pure-react-carousel/src/app'>;
}
declare module 'pure-react-carousel/src/App/__tests__/App.test.jsx' {
  declare module.exports: $Exports<'pure-react-carousel/src/App/__tests__/App.test'>;
}
declare module 'pure-react-carousel/src/App/App.jsx' {
  declare module.exports: $Exports<'pure-react-carousel/src/App/App'>;
}
declare module 'pure-react-carousel/src/App/examples/Example1/Example1.jsx' {
  declare module.exports: $Exports<'pure-react-carousel/src/App/examples/Example1/Example1'>;
}
declare module 'pure-react-carousel/src/App/examples/Example1/index.js' {
  declare module.exports: $Exports<'pure-react-carousel/src/App/examples/Example1/index'>;
}
declare module 'pure-react-carousel/src/App/examples/Example10/CustomSpinner.jsx' {
  declare module.exports: $Exports<'pure-react-carousel/src/App/examples/Example10/CustomSpinner'>;
}
declare module 'pure-react-carousel/src/App/examples/Example10/Example10.jsx' {
  declare module.exports: $Exports<'pure-react-carousel/src/App/examples/Example10/Example10'>;
}
declare module 'pure-react-carousel/src/App/examples/Example10/index.js' {
  declare module.exports: $Exports<'pure-react-carousel/src/App/examples/Example10/index'>;
}
declare module 'pure-react-carousel/src/App/examples/Example2/Example2.jsx' {
  declare module.exports: $Exports<'pure-react-carousel/src/App/examples/Example2/Example2'>;
}
declare module 'pure-react-carousel/src/App/examples/Example2/index.js' {
  declare module.exports: $Exports<'pure-react-carousel/src/App/examples/Example2/index'>;
}
declare module 'pure-react-carousel/src/App/examples/Example3/Example3.jsx' {
  declare module.exports: $Exports<'pure-react-carousel/src/App/examples/Example3/Example3'>;
}
declare module 'pure-react-carousel/src/App/examples/Example3/index.js' {
  declare module.exports: $Exports<'pure-react-carousel/src/App/examples/Example3/index'>;
}
declare module 'pure-react-carousel/src/App/examples/Example4/Example4.jsx' {
  declare module.exports: $Exports<'pure-react-carousel/src/App/examples/Example4/Example4'>;
}
declare module 'pure-react-carousel/src/App/examples/Example4/index.js' {
  declare module.exports: $Exports<'pure-react-carousel/src/App/examples/Example4/index'>;
}
declare module 'pure-react-carousel/src/App/examples/Example5/Example5.jsx' {
  declare module.exports: $Exports<'pure-react-carousel/src/App/examples/Example5/Example5'>;
}
declare module 'pure-react-carousel/src/App/examples/Example5/index.js' {
  declare module.exports: $Exports<'pure-react-carousel/src/App/examples/Example5/index'>;
}
declare module 'pure-react-carousel/src/App/examples/Example6/Example6.jsx' {
  declare module.exports: $Exports<'pure-react-carousel/src/App/examples/Example6/Example6'>;
}
declare module 'pure-react-carousel/src/App/examples/Example6/index.js' {
  declare module.exports: $Exports<'pure-react-carousel/src/App/examples/Example6/index'>;
}
declare module 'pure-react-carousel/src/App/examples/Example7/Example7.jsx' {
  declare module.exports: $Exports<'pure-react-carousel/src/App/examples/Example7/Example7'>;
}
declare module 'pure-react-carousel/src/App/examples/Example7/index.js' {
  declare module.exports: $Exports<'pure-react-carousel/src/App/examples/Example7/index'>;
}
declare module 'pure-react-carousel/src/App/examples/Example7/redux/demo-dux.js' {
  declare module.exports: $Exports<'pure-react-carousel/src/App/examples/Example7/redux/demo-dux'>;
}
declare module 'pure-react-carousel/src/App/examples/Example7/redux/demo-store.js' {
  declare module.exports: $Exports<'pure-react-carousel/src/App/examples/Example7/redux/demo-store'>;
}
declare module 'pure-react-carousel/src/App/examples/Example7/SlideComponent/index.js' {
  declare module.exports: $Exports<'pure-react-carousel/src/App/examples/Example7/SlideComponent/index'>;
}
declare module 'pure-react-carousel/src/App/examples/Example7/SlideComponent/SlideComponent.jsx' {
  declare module.exports: $Exports<'pure-react-carousel/src/App/examples/Example7/SlideComponent/SlideComponent'>;
}
declare module 'pure-react-carousel/src/App/examples/Example8/Example8.jsx' {
  declare module.exports: $Exports<'pure-react-carousel/src/App/examples/Example8/Example8'>;
}
declare module 'pure-react-carousel/src/App/examples/Example8/index.js' {
  declare module.exports: $Exports<'pure-react-carousel/src/App/examples/Example8/index'>;
}
declare module 'pure-react-carousel/src/App/examples/Example9/Example9.jsx' {
  declare module.exports: $Exports<'pure-react-carousel/src/App/examples/Example9/Example9'>;
}
declare module 'pure-react-carousel/src/App/examples/Example9/index.js' {
  declare module.exports: $Exports<'pure-react-carousel/src/App/examples/Example9/index'>;
}
declare module 'pure-react-carousel/src/App/examples/index.js' {
  declare module.exports: $Exports<'pure-react-carousel/src/App/examples/index'>;
}
declare module 'pure-react-carousel/src/ButtonBack/__tests__/ButtonBack.test.jsx' {
  declare module.exports: $Exports<'pure-react-carousel/src/ButtonBack/__tests__/ButtonBack.test'>;
}
declare module 'pure-react-carousel/src/ButtonBack/ButtonBack.jsx' {
  declare module.exports: $Exports<'pure-react-carousel/src/ButtonBack/ButtonBack'>;
}
declare module 'pure-react-carousel/src/ButtonBack/index.js' {
  declare module.exports: $Exports<'pure-react-carousel/src/ButtonBack/index'>;
}
declare module 'pure-react-carousel/src/ButtonFirst/__tests__/ButtonFirst.test.jsx' {
  declare module.exports: $Exports<'pure-react-carousel/src/ButtonFirst/__tests__/ButtonFirst.test'>;
}
declare module 'pure-react-carousel/src/ButtonFirst/ButtonFirst.jsx' {
  declare module.exports: $Exports<'pure-react-carousel/src/ButtonFirst/ButtonFirst'>;
}
declare module 'pure-react-carousel/src/ButtonFirst/index.js' {
  declare module.exports: $Exports<'pure-react-carousel/src/ButtonFirst/index'>;
}
declare module 'pure-react-carousel/src/ButtonLast/__tests__/ButtonLast.test.jsx' {
  declare module.exports: $Exports<'pure-react-carousel/src/ButtonLast/__tests__/ButtonLast.test'>;
}
declare module 'pure-react-carousel/src/ButtonLast/ButtonLast.jsx' {
  declare module.exports: $Exports<'pure-react-carousel/src/ButtonLast/ButtonLast'>;
}
declare module 'pure-react-carousel/src/ButtonLast/index.js' {
  declare module.exports: $Exports<'pure-react-carousel/src/ButtonLast/index'>;
}
declare module 'pure-react-carousel/src/ButtonNext/__tests__/ButtonNext.test.jsx' {
  declare module.exports: $Exports<'pure-react-carousel/src/ButtonNext/__tests__/ButtonNext.test'>;
}
declare module 'pure-react-carousel/src/ButtonNext/ButtonNext.jsx' {
  declare module.exports: $Exports<'pure-react-carousel/src/ButtonNext/ButtonNext'>;
}
declare module 'pure-react-carousel/src/ButtonNext/index.js' {
  declare module.exports: $Exports<'pure-react-carousel/src/ButtonNext/index'>;
}
declare module 'pure-react-carousel/src/ButtonPlay/__tests__/ButtonPlay.test.jsx' {
  declare module.exports: $Exports<'pure-react-carousel/src/ButtonPlay/__tests__/ButtonPlay.test'>;
}
declare module 'pure-react-carousel/src/ButtonPlay/ButtonPlay.jsx' {
  declare module.exports: $Exports<'pure-react-carousel/src/ButtonPlay/ButtonPlay'>;
}
declare module 'pure-react-carousel/src/ButtonPlay/index.js' {
  declare module.exports: $Exports<'pure-react-carousel/src/ButtonPlay/index'>;
}
declare module 'pure-react-carousel/src/CarouselProvider/__tests__/CarouselProvider.test.jsx' {
  declare module.exports: $Exports<'pure-react-carousel/src/CarouselProvider/__tests__/CarouselProvider.test'>;
}
declare module 'pure-react-carousel/src/CarouselProvider/CarouselProvider.jsx' {
  declare module.exports: $Exports<'pure-react-carousel/src/CarouselProvider/CarouselProvider'>;
}
declare module 'pure-react-carousel/src/CarouselProvider/index.js' {
  declare module.exports: $Exports<'pure-react-carousel/src/CarouselProvider/index'>;
}
declare module 'pure-react-carousel/src/Dot/__tests__/Dot.test.jsx' {
  declare module.exports: $Exports<'pure-react-carousel/src/Dot/__tests__/Dot.test'>;
}
declare module 'pure-react-carousel/src/Dot/Dot.jsx' {
  declare module.exports: $Exports<'pure-react-carousel/src/Dot/Dot'>;
}
declare module 'pure-react-carousel/src/Dot/index.js' {
  declare module.exports: $Exports<'pure-react-carousel/src/Dot/index'>;
}
declare module 'pure-react-carousel/src/DotGroup/__tests__/DotGroup.test.jsx' {
  declare module.exports: $Exports<'pure-react-carousel/src/DotGroup/__tests__/DotGroup.test'>;
}
declare module 'pure-react-carousel/src/DotGroup/DotGroup.jsx' {
  declare module.exports: $Exports<'pure-react-carousel/src/DotGroup/DotGroup'>;
}
declare module 'pure-react-carousel/src/DotGroup/index.js' {
  declare module.exports: $Exports<'pure-react-carousel/src/DotGroup/index'>;
}
declare module 'pure-react-carousel/src/helpers/component-config.js' {
  declare module.exports: $Exports<'pure-react-carousel/src/helpers/component-config'>;
}
declare module 'pure-react-carousel/src/helpers/index.js' {
  declare module.exports: $Exports<'pure-react-carousel/src/helpers/index'>;
}
declare module 'pure-react-carousel/src/Image/__tests__/Image.test.jsx' {
  declare module.exports: $Exports<'pure-react-carousel/src/Image/__tests__/Image.test'>;
}
declare module 'pure-react-carousel/src/Image/Image.jsx' {
  declare module.exports: $Exports<'pure-react-carousel/src/Image/Image'>;
}
declare module 'pure-react-carousel/src/Image/index.js' {
  declare module.exports: $Exports<'pure-react-carousel/src/Image/index'>;
}
declare module 'pure-react-carousel/src/ImageWithZoom/__tests__/ImageWithZoom.test.jsx' {
  declare module.exports: $Exports<'pure-react-carousel/src/ImageWithZoom/__tests__/ImageWithZoom.test'>;
}
declare module 'pure-react-carousel/src/ImageWithZoom/ImageWithZoom.jsx' {
  declare module.exports: $Exports<'pure-react-carousel/src/ImageWithZoom/ImageWithZoom'>;
}
declare module 'pure-react-carousel/src/ImageWithZoom/index.js' {
  declare module.exports: $Exports<'pure-react-carousel/src/ImageWithZoom/index'>;
}
declare module 'pure-react-carousel/src/index.js' {
  declare module.exports: $Exports<'pure-react-carousel/src/index'>;
}
declare module 'pure-react-carousel/src/Slide/__tests__/Slide.test.jsx' {
  declare module.exports: $Exports<'pure-react-carousel/src/Slide/__tests__/Slide.test'>;
}
declare module 'pure-react-carousel/src/Slide/index.js' {
  declare module.exports: $Exports<'pure-react-carousel/src/Slide/index'>;
}
declare module 'pure-react-carousel/src/Slide/Slide.jsx' {
  declare module.exports: $Exports<'pure-react-carousel/src/Slide/Slide'>;
}
declare module 'pure-react-carousel/src/Slider/__tests__/Slider.test.jsx' {
  declare module.exports: $Exports<'pure-react-carousel/src/Slider/__tests__/Slider.test'>;
}
declare module 'pure-react-carousel/src/Slider/GetScrollParent.js' {
  declare module.exports: $Exports<'pure-react-carousel/src/Slider/GetScrollParent'>;
}
declare module 'pure-react-carousel/src/Slider/index.js' {
  declare module.exports: $Exports<'pure-react-carousel/src/Slider/index'>;
}
declare module 'pure-react-carousel/src/Slider/Slider.jsx' {
  declare module.exports: $Exports<'pure-react-carousel/src/Slider/Slider'>;
}
declare module 'pure-react-carousel/src/Spinner/index.js' {
  declare module.exports: $Exports<'pure-react-carousel/src/Spinner/index'>;
}
declare module 'pure-react-carousel/src/Spinner/Spinner.jsx' {
  declare module.exports: $Exports<'pure-react-carousel/src/Spinner/Spinner'>;
}
declare module 'pure-react-carousel/src/Store/__tests__/Store.test.jsx' {
  declare module.exports: $Exports<'pure-react-carousel/src/Store/__tests__/Store.test'>;
}
declare module 'pure-react-carousel/src/Store/Store.jsx' {
  declare module.exports: $Exports<'pure-react-carousel/src/Store/Store'>;
}
declare module 'pure-react-carousel/src/Store/WithStore.jsx' {
  declare module.exports: $Exports<'pure-react-carousel/src/Store/WithStore'>;
}
