// flow-typed signature: 7a8e49c9c49e5a0f25800c5a51cb1a46
// flow-typed version: <<STUB>>/webpack-subresource-integrity_v^1.3.0/flow_v0.89.0

/**
 * This is an autogenerated libdef stub for:
 *
 *   'webpack-subresource-integrity'
 *
 * Fill this stub out by replacing all the `any` types.
 *
 * Once filled out, we encourage you to share your work with the
 * community by sending a pull request to:
 * https://github.com/flowtype/flow-typed
 */

declare module 'webpack-subresource-integrity' {
  declare module.exports: any;
}

/**
 * We include stubs for each file inside this npm package in case you need to
 * require those files directly. Feel free to delete any files that aren't
 * needed.
 */
declare module 'webpack-subresource-integrity/jmtp' {
  declare module.exports: any;
}

declare module 'webpack-subresource-integrity/util' {
  declare module.exports: any;
}

// Filename aliases
declare module 'webpack-subresource-integrity/index' {
  declare module.exports: $Exports<'webpack-subresource-integrity'>;
}
declare module 'webpack-subresource-integrity/index.js' {
  declare module.exports: $Exports<'webpack-subresource-integrity'>;
}
declare module 'webpack-subresource-integrity/jmtp.js' {
  declare module.exports: $Exports<'webpack-subresource-integrity/jmtp'>;
}
declare module 'webpack-subresource-integrity/util.js' {
  declare module.exports: $Exports<'webpack-subresource-integrity/util'>;
}
