// flow-typed signature: 71f3f8b8e0c8b1e3aad8972ddf18f540
// flow-typed version: <<STUB>>/with-url-state_v^2.0.2/flow_v0.90.0

/**
 * This is an autogenerated libdef stub for:
 *
 *   'with-url-state'
 *
 * Fill this stub out by replacing all the `any` types.
 *
 * Once filled out, we encourage you to share your work with the
 * community by sending a pull request to:
 * https://github.com/flowtype/flow-typed
 */

declare module 'with-url-state' {
  declare module.exports: any;
}

/**
 * We include stubs for each file inside this npm package in case you need to
 * require those files directly. Feel free to delete any files that aren't
 * needed.
 */
declare module 'with-url-state/dist/withUrlState' {
  declare module.exports: any;
}

// Filename aliases
declare module 'with-url-state/dist/withUrlState.js' {
  declare module.exports: $Exports<'with-url-state/dist/withUrlState'>;
}
